name       : micro
version    : 2.0.8
release    : 21
source     :
    - git|https://github.com/zyedidia/micro.git : v2.0.8
license    : MIT
homepage   : https://micro-editor.github.io
component  : editor
summary    : Micro is a terminal-based text editor that aims to be easy to use and intuitive
description: |
    Micro is a terminal-based text editor that aims to be easy to use and intuitive, while also taking advantage of the full capabilities of modern terminals
extract    : no
networking : yes
builddeps  :
    - git
    - golang
rundeps    :
    - xclip
setup      : |
    mkdir -p micro-$version/src/github.com/zyedidia/micro
    cp -R $sources/micro.git/. micro-$version/src/github.com/zyedidia/micro/
install    : |
    export GOPATH=$workdir
    cd src/github.com/zyedidia/micro
    %make install-all
    install -Dm00755 $GOPATH/bin/micro $installdir/usr/bin/micro
    install -Dm00644 $workdir/src/github.com/zyedidia/micro/assets/packaging/micro.1 $installdir/usr/share/man/man1/micro.1
