name       : micro
version    : 1.1.2
release    : 1
source     :
    - https://github.com/zyedidia/micro/archive/v1.1.2.tar.gz : 2f865c792714c12e0075b0123fe795bb0e09678ae507ec721cca49847c3d6a52
license    : MIT
component  : editor
summary    : Micro is a terminal-based text editor that aims to be easy to use and intuitive
description: |
    Micro is a terminal-based text editor that aims to be easy to use and intuitive, while also taking advantage of the full capabilities of modern terminals
extract    : no
builddeps  :
    - git
    - golang
setup      : |
    mkdir -p micro-$version/src/github.com/zyedidia/micro
    tar -xvf $sources/v$version.tar.gz -C micro-$version/src/github.com/zyedidia/micro --strip-components=1
install    : |
    export GOPATH=$workdir
    cd src/github.com/zyedidia/micro
    %make_install
    install -D -m 00755 $GOPATH/bin/micro $installdir/usr/bin/micro