name       : micro
version    : 1.4.0
release    : 11
source     :
    - https://github.com/zyedidia/micro/releases/download/v1.4.0/micro-1.4.0-src.tar.gz : 2b36a4e7f69e6bb48591527454a93ff781db8e8a94dc646e934f6a3de862d40b
license    : MIT
component  : editor
summary    : Micro is a terminal-based text editor that aims to be easy to use and intuitive
description: |
    Micro is a terminal-based text editor that aims to be easy to use and intuitive, while also taking advantage of the full capabilities of modern terminals
extract    : no
networking : yes
builddeps  :
    - git
    - golang
rundeps    :
    - xclip
setup      : |
    export GOPATH=$workdir
    mkdir -p micro-$version/src/github.com/zyedidia/micro
    tar -xf $sources/micro-$version-src.tar.gz -C micro-$version/src/github.com/zyedidia/micro --strip-components=1
install    : |
    export GOPATH=$workdir
    cd src/github.com/zyedidia/micro
    go get -u github.com/blang/semver
    %make install-all
    install -D -m 00755 $GOPATH/bin/micro $installdir/usr/bin/micro
