name       : micro
version    : 1.3.2
release    : 9
source     :
    - https://github.com/zyedidia/micro/releases/download/v1.3.2/micro-1.3.2-src.tar.gz : 1a08301e39353914d7e699e36455bac1fee7d6d5ff1e211499bc10b46d8b35f5
license    : MIT
component  : editor
summary    : Micro is a terminal-based text editor that aims to be easy to use and intuitive
description: |
    Micro is a terminal-based text editor that aims to be easy to use and intuitive, while also taking advantage of the full capabilities of modern terminals
extract    : no
networking : yes
builddeps  :
    - git
    - golang
rundeps    :
    - xclip
setup      : |
    export GOPATH=$workdir
    mkdir -p micro-$version/src/github.com/zyedidia/micro
    tar -xf $sources/micro-$version-src.tar.gz -C micro-$version/src/github.com/zyedidia/micro --strip-components=1
install    : |
    export GOPATH=$workdir
    cd src/github.com/zyedidia/micro
    go get -u github.com/blang/semver
    %make install-all
    install -D -m 00755 $GOPATH/bin/micro $installdir/usr/bin/micro
