name       : micro
version    : 1.2.0
release    : 6
source     :
    - https://github.com/zyedidia/micro/releases/download/v1.2.0/micro-1.2.0-src.tar.gz : a07a065775f3a3e5ba710d3d7491ba7578cb7c44d4a971246e7d2be44eed938d
license    : MIT
component  : editor
summary    : Micro is a terminal-based text editor that aims to be easy to use and intuitive
description: |
    Micro is a terminal-based text editor that aims to be easy to use and intuitive, while also taking advantage of the full capabilities of modern terminals
extract    : no
networking : yes
builddeps  :
    - git
    - golang
rundeps    :
    - xclip
setup      : |
    export GOPATH=$workdir
    mkdir -p micro-$version/src/github.com/zyedidia/micro
    tar -xf $sources/micro-$version-src.tar.gz -C micro-$version/src/github.com/zyedidia/micro --strip-components=1
install    : |
    export GOPATH=$workdir
    cd src/github.com/zyedidia/micro
    go get -u github.com/blang/semver
    %make install-all
    install -D -m 00755 $GOPATH/bin/micro $installdir/usr/bin/micro
