name       : micro
version    : 2.0.1
release    : 14
source     :
    - https://github.com/zyedidia/micro/archive/v2.0.1.tar.gz : dabbc94f58f63b2b2c4589cdfc83e265019f3ac02e13654bf91927f4bc6434ec
    - git|https://github.com/zyedidia/go-bindata.git : 9453701aa0dbd20f88145dbd77c6f50937f17a19
license    : MIT
component  : editor
summary    : Micro is a terminal-based text editor that aims to be easy to use and intuitive
description: |
    Micro is a terminal-based text editor that aims to be easy to use and intuitive, while also taking advantage of the full capabilities of modern terminals
extract    : no
networking : yes
builddeps  :
    - git
    - golang
rundeps    :
    - xclip
setup      : |
    export GOPATH=$workdir
    mkdir -p micro-$version/src/github.com/zyedidia/micro
    tar xf $sources/v$version.tar.gz -C micro-$version/src/github.com/zyedidia/micro --strip-components=1
    cd micro-$version/src/github.com/zyedidia/micro/
    cp -R $sources/go-bindata.git/. tools/go-bindata
    %patch -p1 < $pkgfiles/0001-remove-usages-of-git-as-we-use-a-tarball.patch
install    : |
    export GOPATH=$workdir
    cd src/github.com/zyedidia/micro
    go get -u github.com/blang/semver
    %make install-all
    install -D -m 00755 $GOPATH/bin/micro $installdir/usr/bin/micro
