name       : micro
version    : 1.1.3
release    : 3
source     :
    - https://github.com/zyedidia/micro/releases/download/v1.1.3/micro-1.1.3-src.tar.gz : 7b0824b966b6c1e36f89e2bf40114be2e192aafd05b6a994caecb81d4de63a88
license    : MIT
component  : editor
summary    : Micro is a terminal-based text editor that aims to be easy to use and intuitive
description: |
    Micro is a terminal-based text editor that aims to be easy to use and intuitive, while also taking advantage of the full capabilities of modern terminals
extract    : no
builddeps  :
    - git
    - golang
rundeps    :
    - xclip
setup      : |
    mkdir -p micro-$version/src/github.com/zyedidia/micro
    tar -xvf $sources/micro-$version-src.tar.gz -C micro-$version/src/github.com/zyedidia/micro --strip-components=1
install    : |
    export GOPATH=$workdir
    cd src/github.com/zyedidia/micro
    %make_install
    install -D -m 00755 $GOPATH/bin/micro $installdir/usr/bin/micro
