name       : micro
version    : 2.0.11
release    : 26
source     :
    - git|https://github.com/zyedidia/micro.git : v2.0.11
license    : MIT
homepage   : https://micro-editor.github.io
component  : editor
summary    : Micro is a terminal-based text editor that aims to be easy to use and intuitive
description: |
    Micro is a terminal-based text editor that aims to be easy to use and intuitive, while also taking advantage of the full capabilities of modern terminals
networking : yes
builddeps  :
    - git
    - golang
rundeps    :
    - xclip
build      : |
    %make
install    : |
    install -Dm00755 $workdir/micro $installdir/usr/bin/micro
    install -Dm00644 $workdir/assets/packaging/micro.1 $installdir/usr/share/man/man1/micro.1
